import productimg from "../../assets/img//Product/product3.jpeg"

const product = [
    {
        id: 1,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: false,
    },
    {
        id: 2,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: true,
    },
    {
        id: 3,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: true,
    },
    {
        id: 4,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: false,
    },
    {
        id: 5,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 6,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 7,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 8,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 9,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 10,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 11,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 12,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 13,
        img: productimg,
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 14,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 15,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 16,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: true,
    },
    {
        id: 17,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: false,
    },
    {
        id: 18,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: false,
    },
    {
        id: 19,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: false,
    },
    {
        id: 20,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: false,
        sale: true,
    },
    {
        id: 21,
        img: productimg,
        name: "Подсолнечное масло Oila tanlovi, рафинированное и дезодорированное,",
        describtion: "Lorem ipsum dolor sit amet, consectetur adipiscing ",
        advice: "yoz narsa",
        comments: 10,
        monthpay: 100,
        rate: 5,
        price: 1000,
        oldprice: 1200,
        discount: true,
        sale: false,
    },
]

export default product 